# Generated by Django 2.1.4 on 2019-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('num', models.BigIntegerField()),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
    ]
