# Generated by Django 2.1.4 on 2019-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20190511_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donetest',
            old_name='date',
            new_name='date_started',
        ),
    ]
