# Generated by Django 2.1.4 on 2019-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_donetest_numberofrightanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.CharField(choices=[('Гамильтонов цикл', 'Гамильтонов цикл'), ('Эйлеров цикл', 'Эйлеров цикл')], max_length=50),
        ),
    ]
