# Generated by Django 2.1.4 on 2019-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190512_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_theme',
            field=models.CharField(default='', max_length=50),
        ),
    ]
